apiVersion: apps/v1
kind: Deployment
metadata:
  name: youneed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youneed
  template:
    metadata:
      labels:
        app: youneed
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: youneed
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "9a872722-c647-418c-9c11-62c1d7cea0b0"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "9a872722-c647-418c-9c11-62c1d7cea0b0"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
